# Generated by Django 3.1.5 on 2021-01-17 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.TextField(unique=True)),
                ('score', models.IntegerField()),
                ('category', models.CharField(choices=[('sqli', 'SQLi'), ('xss', 'XSS')], max_length=20)),
                ('teams', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flag들',
            },
        ),
    ]
