# Generated by Django 3.1.5 on 2021-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_csprule_lenrule_regexrule_sqlifilter_xssfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='XssLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.CharField(max_length=20)),
                ('to_team', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=1000)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('succeed', models.BooleanField(default=False)),
                ('csp', models.ManyToManyField(blank=True, to='base.CspRule')),
            ],
            options={
                'verbose_name': 'XSS 로그',
                'verbose_name_plural': 'XSS 로그들',
                'get_latest_by': 'created_at',
            },
        ),
    ]
