# Generated by Django 3.1.5 on 2021-01-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_csprule_lenrule_regexrule_sqlifilter_xssfilter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sqli', 'SQLi'), ('xss', 'XSS')], max_length=20)),
                ('price', models.IntegerField()),
                ('teams', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegexItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('regex_rule', models.ManyToManyField(to='base.RegexRule')),
            ],
            options={
                'verbose_name': '차단 규칙 아이템',
                'verbose_name_plural': '차단 규칙 아이템들',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='LenItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('len_rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.lenrule')),
            ],
            options={
                'verbose_name': '길이 제한 아이템',
                'verbose_name_plural': '길이 제한 아이템들',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='CspItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('csp_rule', models.ManyToManyField(to='base.CspRule')),
            ],
            options={
                'verbose_name': 'CSP 아이템',
                'verbose_name_plural': 'CSP 아이템들',
            },
            bases=('shop.item',),
        ),
    ]
