# Generated by Django 3.1 on 2020-08-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='is_added',
        ),
    ]
