# Generated by Django 3.1 on 2020-08-06 16:24

import core.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('max_len', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '필터',
                'verbose_name_plural': '필터들',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '차단 규칙',
                'verbose_name_plural': '차단 규칙들',
            },
        ),
        migrations.CreateModel(
            name='CspRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rule')),
                ('csp', models.TextField()),
            ],
            options={
                'verbose_name': 'CSP',
                'verbose_name_plural': 'CSP들',
            },
            bases=('core.rule',),
        ),
        migrations.CreateModel(
            name='LenRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rule')),
                ('value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '길이 제한 엄격화 규칙',
                'verbose_name_plural': '길이 제한 엄격화 규칙들',
            },
            bases=('core.rule',),
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.rule')),
                ('regexp', models.TextField()),
            ],
            options={
                'verbose_name': '정규식 차단 규칙',
                'verbose_name_plural': '정규식 차단 규칙들',
            },
            bases=('core.rule',),
        ),
        migrations.CreateModel(
            name='SqliFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filter')),
            ],
            options={
                'verbose_name': 'SQLi 필터',
                'verbose_name_plural': 'SQLi 필터들',
            },
            bases=('core.filter',),
        ),
        migrations.CreateModel(
            name='SstiFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filter')),
            ],
            options={
                'verbose_name': 'SSTI 필터',
                'verbose_name_plural': 'SSTI 필터들',
            },
            bases=('core.filter',),
        ),
        migrations.CreateModel(
            name='XssFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.filter')),
                ('csp_rule_list', models.ManyToManyField(blank=True, to='core.CspRule')),
            ],
            options={
                'verbose_name': 'XSS 필터',
                'verbose_name_plural': 'XSS 필터들',
            },
            bases=('core.filter',),
        ),
        migrations.AddField(
            model_name='filter',
            name='regex_rule_list',
            field=models.ManyToManyField(blank=True, to='core.RegexRule'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('balance', models.BigIntegerField()),
                ('score', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('sqli_filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SQLi_Filter', to='core.sqlifilter')),
                ('ssti_filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SSTI_Filter', to='core.sstifilter')),
                ('xss_filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='XSS_Filter', to='core.xssfilter')),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀들',
            },
            managers=[
                ('objects', core.models.TeamManager()),
            ],
        ),
    ]
