# Generated by Django 3.1 on 2020-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
