# Generated by Django 3.1 on 2020-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
