# Generated by Django 3.1 on 2020-08-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200807_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='max_len',
            field=models.BigIntegerField(default=10000),
        ),
    ]
