# Generated by Django 3.1 on 2020-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200813_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='teamname',
            field=models.CharField(default='NONAME', max_length=20),
        ),
    ]
