# Generated by Django 3.1 on 2020-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200816_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='name',
        ),
        migrations.AddField(
            model_name='sqlifilter',
            name='name',
            field=models.CharField(default='SQLi_filter', max_length=20),
        ),
    ]
