# Generated by Django 3.1 on 2020-08-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200816_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sstifilter',
            name='name',
            field=models.CharField(default='SSTI_filter', max_length=20),
        ),
        migrations.AddField(
            model_name='xssfilter',
            name='name',
            field=models.CharField(default='XSS_filter', max_length=20),
        ),
    ]
