# Generated by Django 3.1 on 2020-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200816_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='name',
        ),
        migrations.AddField(
            model_name='csprule',
            name='name',
            field=models.CharField(default='csprule', max_length=20),
        ),
        migrations.AddField(
            model_name='lenrule',
            name='name',
            field=models.CharField(default='lenrule', max_length=20),
        ),
        migrations.AddField(
            model_name='regexrule',
            name='name',
            field=models.CharField(default='regexrule', max_length=20),
        ),
    ]
