# Generated by Django 3.1 on 2020-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200816_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='max_len',
            field=models.BigIntegerField(default=120),
        ),
    ]
