# Generated by Django 3.1.5 on 2021-01-16 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CspRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('csp', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CSP',
                'verbose_name_plural': 'CSP들',
            },
        ),
        migrations.CreateModel(
            name='LenRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': '길이 제한 엄격화 규칙',
                'verbose_name_plural': '길이 제한 엄격화 규칙들',
            },
        ),
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('regexp', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '정규식 차단 규칙',
                'verbose_name_plural': '정규식 차단 규칙들',
            },
        ),
        migrations.CreateModel(
            name='XssFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_len', models.PositiveSmallIntegerField(default=120)),
                ('csp_rule_list', models.ManyToManyField(blank=True, to='base.CspRule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('regex_rule_list', models.ManyToManyField(blank=True, to='base.RegexRule')),
            ],
            options={
                'verbose_name': 'XSS 필터',
                'verbose_name_plural': 'XSS 필터들',
            },
        ),
        migrations.CreateModel(
            name='SqliFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_len', models.PositiveSmallIntegerField(default=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('regex_rule_list', models.ManyToManyField(blank=True, to='base.RegexRule')),
            ],
            options={
                'verbose_name': 'SQLi 필터',
                'verbose_name_plural': 'SQLi 필터들',
            },
        ),
    ]
