# Generated by Django 3.1 on 2020-08-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XssTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.CharField(max_length=20)),
                ('to_team', models.CharField(max_length=20)),
                ('csp', models.CharField(max_length=10000)),
                ('query', models.CharField(max_length=10000)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('succeed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'XSS 공격 시도',
                'verbose_name_plural': 'XSS 공격 시도들',
            },
        ),
    ]
