# Generated by Django 3.1 on 2020-08-14 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsstrial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
