# Generated by Django 3.1 on 2020-08-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xss', '0003_auto_20200814_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xsstrial',
            options={'get_latest_by': 'created_at', 'verbose_name': 'XSS 공격 시도', 'verbose_name_plural': 'XSS 공격 시도들'},
        ),
    ]
