# Generated by Django 3.1 on 2020-08-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200816_1458'),
        ('xss', '0004_auto_20200815_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='XssLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.CharField(max_length=20)),
                ('to_team', models.CharField(max_length=20)),
                ('query', models.CharField(max_length=1000)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('succeed', models.BooleanField(default=False)),
                ('csp', models.ManyToManyField(blank=True, to='core.CspRule')),
            ],
            options={
                'verbose_name': 'XSS 공격 시도',
                'verbose_name_plural': 'XSS 공격 시도들',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.DeleteModel(
            name='XssTrial',
        ),
    ]
