# Generated by Django 3.1 on 2020-08-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sqli', 'SQLi'), ('xss', 'XSS'), ('ssti', 'SSTI')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('teams', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '아이템',
                'verbose_name_plural': '아이템들',
            },
        ),
        migrations.CreateModel(
            name='RegexItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('regex_rule', models.ManyToManyField(to='core.RegexRule')),
            ],
            options={
                'verbose_name': '차단 규칙 아이템',
                'verbose_name_plural': '차단 규칙 아이템들',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='LenItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('len_rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lenrule')),
            ],
            options={
                'verbose_name': '길이 제한 아이템',
                'verbose_name_plural': '길이 제한 아이템들',
            },
            bases=('shop.item',),
        ),
        migrations.CreateModel(
            name='CspItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.item')),
                ('csp_rule', models.ManyToManyField(to='core.CspRule')),
            ],
            options={
                'verbose_name': 'CSP 아이템',
                'verbose_name_plural': 'CSP 아이템들',
            },
            bases=('shop.item',),
        ),
    ]
